### ISSUE TITLE
allow filtering reviews

### ISSUE THREAD

**Issue by cmeury** [mehmetbajin/gt-course-surveys#23]
As courses change in difficulty, quality and content ove time, the older reviews might not be relevant anymore. It might make sense to use a time-frame to display the text reviews and averages. Could be turned on by default or added as an option.

**Comment by mehmetbajin** [comment]
It may be better to provide filtering options in every view (by semester, by difficulty, by workload, etc.).

**Comment by ramachandranms** [comment]
I was thinking if we could have a global toggle switch to show only last taught term reviews/ratings. thoughts ?

**Comment by mehmetbajin** [comment]
Why limit to last taught term?

Also, global is worrisome, because grades views would not benefit from filtering by semester. After all, the value comes mainly from being able to see trends across time.

IMO, allowing filtering by the various attributes of a review (semester, difficulty, workload, rating) in the course review views (/reviews/:courseId) would be a great start.

_Disclaimer: Earlier posts in this thread were more relevant to the prior version of the app._

**Comment by mehmetbajin** [comment]
Review filtering has been added. Feedback welcome!
